# Generated by Django 3.0.8 on 2020-07-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name_plural': 'Music'},
        ),
        migrations.RemoveField(
            model_name='music',
            name='ISMN',
        ),
    ]
