# Generated by Django 3.0.8 on 2020-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20200721_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterField(
            model_name='history',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
